services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: redmine_development
      POSTGRES_USER: redmine
      POSTGRES_PASSWORD: my_password
    volumes:
      - ./docker/vol/db_data:/var/lib/postgresql/data

  redmine:
    image: redmine:6.0
    restart: always
    ports:
      - "3000:3000"
    environment:
      REDMINE_PLUGINS_MIGRATE: "true"
    depends_on:
      - db
      - mailhog
    volumes:
      - ./docker/vol/redmine_data:/usr/src/redmine/files
      - .:/usr/src/redmine/plugins/redmine_batched_notifications
      - ./docker/config/configuration.yml:/usr/src/redmine/config/configuration.yml
      - ./docker/config/database.yml:/usr/src/redmine/config/database.yml

  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    logging:
      driver: "none"
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI